import "./services/commons-bot.test.js";
import "./cli/cli.test.js";
import "./cli/post-results-cli.test.js";
import "./core/job-actions.test.js";
import "./core/submission-entries.test.js";
import "./core/validation-scoring.test.js";
import "./infra/job-history.test.js";
import "./parsers/submitting-parser.test.js";
import "./parsers/voting-parser.test.js";
import "./renderers/renderers.test.js";
import "./renderers/voting-index.test.js";
import "./web/maintenance-review.test.js";
import "./web/publish-review.test.js";
import "./workflows/maintenance-publish.test.js";
import "./workflows/post-results-maintenance.test.js";
import "./workflows/publish-service.test.js";
import "./integration/workflow-integration.test.js";
import { run } from "./support/harness.js";

void run();
